### ISSUE TITLE
Conversion output "// for non-Arduino builds..."

### ISSUE THREAD

**Issue by l0l0l0** [bitbank2/image_to_c#11]
Hello, 
I'm using the exe for windows and I tried to convert my gif, but I can't compile them with my arduino project.
I have this error : 

error: invalid preprocessing directive #i

I noticed that in the header I had a message "// for non-Arduino builds...! "
am I doing something wrong?

**Comment by bitbank2** [comment]
I need more info to understand the error you're getting. Can you send the whole error message along with the relevant lines of the text file? I don't use Windows, but it shouldn't matter. I use this tool's output on Arduino Linux, MacOS and non-Arduino embedded builds.

**Comment by l0l0l0** [comment]
when converting my gif I have no error...here is the header:

`//
// Nolan
// Data size = 11637 bytes
//
// GIF, Compression=LZW, Size: 64 x 64, 8-Bpp
// 2 frames
//
// for non-Arduino builds...
#ifndef PROGMEM
#define PROGMEM
#endif
const uint8_t Nolan[] PROGMEM = {
	0x47,0x49,0x46,0x38,0x39,0x61,0x40,0x00,0x40,0x00,0xf7,0x00,0x00,0x07,0x05,0x0b,
	0x09,0x07,0x0e,0x0b,0x09,0x0e,0x0b,0x09,0x11,0x0e,0x0c,0x13,0x0f,0x0e,0x16,0x10,
	0x0d,0x13,0x1a,0x0f,0x13,0x10,0x0f,0x18,0x14,0x11,0x16,0x14,0x13,0x1c,0x16,0x15,
	0x1d,0x19,0x13,0x18,0x1d,0x17,0x1b,0x1a,0x17,0x1d,0x18,0x18,0x1e,0x27,0x11,0x11,
	0x26,0x1a,0x1a,0x31,0x14,0x13,0x36,0x1f,0x1b,0x18,0x17,0x20,0x1b,0x1a,0x23,0x1c,
	0x1b,0x20,0x1e,0x1e,0x27,0x22,0x1c,0x21,0x20,0x1f,0x24,0x2e,0x23,0x24,0x22,0x23,
	0x2a,0x25,0x22,0x28,0x2e,0x2c,0x2c,0x36,0x29,0x2a,0x25,0x27,0x31,0x2a,0x2b,0x36,
	0x34,0x33,0x32,0x3c,0x31,0x35,0x3b,0x3c,0x36,0x31,0x32,0x3c,0x41,0x16,0x16,0x4a,
	0x1f,0x1d,0x40,0x27,0x1f,0x44,0x2f,0x25,0x52,0x26,0x22,0x4e,0x35,0x2a,0x5f,0x30,`

when I compile my arduino project here is the error :

`C:\Users\lduvoisi\Desktop\Bitmaps\Bitmaps\Nolan.h:17:10: error: invalid preprocessing directive #i
   17 |          0 x 3 6 , 0 x 1 f , 0 x 1 b , 0 x 1 8 , 0 x 1 7 , 0 x 2 0 , 0 x 1 b , 0 x 1 a , 0 x 2 3 , 0 x 1 c , 0 x 1 b , 0 x 2 0 , 0 x 1 e , 0 x 1 e , 0 x 2 7 , 0 x 2 2 ,   
      |          ^
C:\Users\lduvoisi\Desktop\Bitmaps\Bitmaps\Nolan.h:19:10: error: invalid preprocessing directive #d
   19 |          0 x 2 c , 0 x 3 6 , 0 x 2 9 , 0 x 2 a , 0 x 2 a , 0 x 2 b , 0 x 3 6 , 0 x 3 4 , 0 x 3 3 , 0 x 3 2 , 0 x 4 1 , 0 x 1 6 , 0 x 1 6 , 0 x 4 a , 0 x 1 f , 0 x 1 d ,   
      |          ^
C:\Users\lduvoisi\Desktop\Bitmaps\Bitmaps\Nolan.h:21:10: error: invalid preprocessing directive #e
   21 |          0 x 3 1 , 0 x 2 8 , 0 x 5 d , 0 x 3 8 , 0 x 2 e , 0 x 4 7 , 0 x 3 7 , 0 x 3 1 , 0 x 5 6 , 0 x 3 c , 0 x 3 1 , 0 x 6 c , 0 x 3 d , 0 x 3 2 , 0 x 7 5 , 0 x 3 b ,   
      |          ^

Using library SmartMatrix at version 4.0.3 in folder: \\home\lduvoisi\Mes Documents\Arduino\libraries\SmartMatrix`

**Comment by bitbank2** [comment]
It appears that whatever compiler you're using is not understanding the double slash "//" which denotes that everything after it on the line should be treated as a comment. C99 and later support double slash comments. Are you using a very old compiler? If so, remove the comment lines and try it again.

**Comment by l0l0l0** [comment]
no that's not it (Arduino15\packages\teensy\tools\teensy-compile\11.3.1/arm/bin/arm-none-eabi-g++)

I will try to convert my gif with linux

**Comment by bitbank2** [comment]
oh - perhaps it's the newline + carriage return versus just carriage return difference.

**Comment by l0l0l0** [comment]
I just converted it with Linux and I no longer have any problems!
Thanks anyway for the help
