### ISSUE TITLE
App does not open and asks for api-ms-win-core-path-l1-1-0.dll file

### ISSUE THREAD

**Issue by rtek1000** [bitbank2/image_to_c#12]
Hello,

I tried running the Windows application, but it didn't open.

> - Asks for api-ms-win-core-path-l1-1-0.dll

I also saw that there is a python script, but it didn't open in Xubuntu:

> $ ./Image2cGUI.py 
> ': Invalid argument @ error/blob.c/OpenBlob/2924.
> import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
> ': Invalid argument @ error/blob.c/OpenBlob/2924.
> import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
> ': Invalid argument @ error/blob.c/OpenBlob/2924.
> import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
> ': Invalid argument @ error/blob.c/OpenBlob/2924.
> import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
> import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
> ./Image2cGUI.py: line 6: $'\r': command not found
> ./Image2cGUI.py: line 8: syntax error near unexpected token `('
> '/Image2cGUI.py: line 8: `def is_module_installed(module_name):

**Comment by bitbank2** [comment]
This is why I don't like to release pre-built binaries. The best way to use all of my tools is to just run make. On Windows this is more challenging because there isn't a built-in C compiler. I'm sorry I can't help with Windows issues; I don't use it.

**Comment by rtek1000** [comment]
I made some programs with [SharpDevelop 4.4](https://sourceforge.net/projects/sharpdevelop/files/SharpDevelop%204.x/4.4/) and I didn't have many problems, the apps generated are similar to those in Visual Studio, but the current version of VS is very heavy.
