### ISSUE TITLE
Can't Open Files on mac

### ISSUE THREAD

**Issue by 10weeks** [bitbank2/image_to_c#15]
Hi,

i was not able to open any files using the gui on mac. after a bit of digging, i found this:

https://stackoverflow.com/questions/44403566/add-multiple-extensions-in-one-filetypes-mac-tkinter-filedialog-askopenfilenam

and replaced the semicolons with spaces for accepted file types

i was then able to select files.

FYI - im not a coder myself so take it at face value, but hope it can help in some way! thanks for making the software.

P.S. - for any other amateurs like me  - on mac i had to move the image_to_c unix file out of the macos folder and into the same folder as the python gui for it to work

**Comment by bitbank2** [comment]
I didn't develop the Python code and don't work with it, it was contributed by someone else. As long as the command line program works correctly, then I don't have anything to fix.
