### ISSUE TITLE
PlatformIO registry

### ISSUE THREAD

**Issue by embedded-creations** [bitbank2/image_to_c#3]
Did you register AnimatedGIF on PlatformIO?

https://platformio.org/lib/show/10952/AnimatedGIF/

If you did, do you mind using [`pio package publish`](https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html#id1) to publish the latest release?

If you didn't you may run into the same issue I did, where someone registered your GitHub username in PlatformIO and registered your libraries, and now there's no obvious way to publish updates to your own library without making a duplicate registry entry under a different username, while the original out of date registry still has priority.  (Annoying!)

I ended up accidentally adding a [duplicate registry entry](https://platformio.org/lib/show/11769/AnimatedGIF) for AnimatedGIF as I thought `pio package publish` would know to update the existing registry entry for AnimatedGIF, and not create a duplicate.  I used `pio package unpublish` and I think it's in the process of being removed.  At least "AnimatedGIF" no longer shows up when I [search for libraries under my username](https://platformio.org/lib/search?query=owner:embedded-creations).

**Comment by bitbank2** [comment]
I don't use PlatformIO, so I have no skin in that game. I saw some of my Arduino libraries listed in there and thought that there was some automated process which pulls them in from the Arduino library manager. I just have too many things going on to start working with a new dev system and tools.

**Comment by embedded-creations** [comment]
I hear you, I said the same thing until I started using the [WLED project](https://github.com/Aircoookie/WLED) and found it was a much better experience compiling that large project with their PlatformIO configuration than with the Arduino IDE.  I haven't switched over yet, I'm still compiling my other projects with Arduino, but I see the appeal and will likely move more of my projects there slowly over time.

If you do ever want to claim your "bitbank2" name on PlatformIO, you can see it was surprisingly painless for me to claim "pixelmatix":

https://community.platformio.org/t/how-to-handle-someone-registering-my-library/19195

**Comment by bitbank2** [comment]
Thanks for the info. I may do this in the near future.
