### ISSUE TITLE
Not generating .h

### ISSUE THREAD

**Issue by Zaido5** [bitbank2/image_to_c#5]
Hi Bitbank2! 

Sorry for bothering you with this. I'm new to this so please bare with me. I am trying to use your image_to_c64.exe file but I am having issues. I open the command prompt and enter the following commands:

C:\Users\Zaido5\Desktop>cd ImagetoC

C:\Users\Zaido5\Desktop\ImagetoC>Start image_to_c64.exe

Output: 

C:\Users\Zaido5\Desktop\ImagetoC>

Nothing seems to happen and I'm sure I'm not doing this correctly. Any advice or help would be really appreciated. Thank you in advanced.

**Comment by bitbank2** [comment]
Instead of typing "start", just type the name of the program, the file you want to convert to a .H and then pipe it (>) to the output file.
e.g.
image_to_c64.exe myimage.jpg > myimage.h

**Comment by Zaido5** [comment]
Thank you bit! I got it to work :) I am noticing that the frame refresh is quite slow, is there a way you recommend to speed it up? For reference I am using an ESP32.

also I had written a blurb about not getting the .h to work and I resolved that myself.

Thank you again! You are great!

**Comment by bitbank2** [comment]
Sorry, what frame refresh is slow? If you're using my other imaging libraries, open an issue with the correct library.
