### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Dario-Ciceri** [bitbank2/image_to_c#6]
could you please explain how to use it to generate .h files? I don't know how to run this type of file since it immediately auto-close, also where the file is supposed to be find? thanks

**Comment by bitbank2** [comment]
If you run it with no parameters, it shows you exactly how to use it (prints to standard out). If you run it from a GUI and the terminal output closes immediately, you won't see it:

Usage: image_to_c <filename>
output is written to stdout
example:

image_to_c ./test.jpg > test.h

**Comment by ghost** [comment]
I get this from terminal:
`Lees-iMac:MacOS lee$ image_to_c 1.png > 1.h
-bash: image_to_c: command not found`
but it does give me an empty 1.h file in the dist/MacOS folder

**Comment by bitbank2** [comment]
The MacOS default execution path doesn't include "." (current directory), so you need to be explicit:

./image_to_c input.png > output.h
(see the ./ above)
