### ISSUE TITLE
invalid preprocessing directive error 

### ISSUE THREAD

**Issue by Yosef-Bunick** [bitbank2/image_to_c#7]
i used the image_to_c64.exe in the command prompt to make this out.h file, and it keeps giving me this error code. i tried with a few others but it gave me the same error, can you help?
it seems to work with the badgers, but not the orb or any others i make, 
i am trying to use it in the animated gif, tft_espi_memory
i included
 #include "../test_images/out.h"
and  #define GIF_IMAGE orb2 

in file included from C:\Users\student\Documents\Arduino\TFT_eSPI_memory2\TFT_eSPI_memory2.ino:36:0:
c:\users\student\documents\arduino\libraries\animatedgif\test_images\out.h:17:4: error: invalid preprocessing directive #i
    0 x 1 1 , 0 x 1 1 , 0 x 3 1 , 0 x 1 1 , 0 x 1 3 , 0 x 3 3 , 0 x 1 1 , 0 x 1 2 , 0 x 3 1 , 0 x 1 1 , 0 x 1 3 , 0 x 3 4 , 0 x 1 1 , 0 x 1 3 , 0 x 3 6 , 0 x 1 1 , 
 
    ^
c:\users\student\documents\arduino\libraries\animatedgif\test_images\out.h:19:4: error: invalid preprocessing directive #d
    0 x 3 c , 0 x 1 1 , 0 x 1 6 , 0 x 3 b , 0 x 1 2 , 0 x 1 8 , 0 x 3 d , 0 x 1 1 , 0 x 1 7 , 0 x 4 0 , 0 x 1 2 , 0 x 1 9 , 0 x 4 3 , 0 x 1 3 , 0 x 1 c , 0 x 4 a , 
 
    ^
c:\users\student\documents\arduino\libraries\animatedgif\test_images\out.h:21:4: error: invalid preprocessing directive #e
    0 x 2 2 , 0 x 5 3 , 0 x 1 c , 0 x 2 4 , 0 x 5 4 , 0 x 1 4 , 0 x 2 2 , 0 x 5 c , 0 x 1 a , 0 x 2 8 , 0 x 5 b , 0 x 2 4 , 0 x 2 8 , 0 x 5 9 , 0 x 3 3 , 0 x 2 b , 
 
    ^

exit status 1

Compilation error: exit status 1

**Comment by bitbank2** [comment]
Can you include the out.h here so that I can see it? The errors look like something else is going wrong.

**Comment by Yosef-Bunick** [comment]
it is not supporting the .h file so i put it in a zip, hopefuly it goes through

[out - Copy.zip](https://github.com/bitbank2/image_to_c/files/11366887/out.-.Copy.zip)

**Comment by bitbank2** [comment]
The file looks fine, but it is > 416K of data. Are you running out of FLASH?

**Comment by Yosef-Bunick** [comment]
i don't think so, the only error I'm getting is the invalid preprocessing directive*

**Comment by bitbank2** [comment]
If you look at the contents of the H file you sent me, there's nothing wrong with it, it's just very large.

**Comment by Yosef-Bunick** [comment]
is there a way to play a larger gif file in the animatedgif tft_espi_memory?

**Comment by Yosef-Bunick** [comment]
is there a way to play the gif through the SD card without the flash memory problem?

**Comment by bitbank2** [comment]
I did a test with a 362MB file from an SD card, so there's no size limit. Take a look at the "play_all_sd_files" example.

**Comment by Yosef-Bunick** [comment]
how does it work? how do i configure the pins? and which file do i put the gif in? does it loop or play multiple files? is there a button or swipe to switch videos?

**Comment by Yosef-Bunick** [comment]
it uploaded, and lit up white, and then went back black.. what type of file do i want on the sd card? what folder should i use?

**Comment by bitbank2** [comment]
All of these questions depend on your setup. The file should be a normal GIF file. You can mount the file anywhere you want. All that needs to happen is that you need to open the correct file and pass the data to the AnimatedGIF library, then display the pixels. It's beyond the scope of this library to adapt to every possible permutation of hardware.

**Comment by Yosef-Bunick** [comment]
so light up and black means its working? how do i open and pass the data to the AnimatedGIF library?
 i should write #include "xyz.gif" and then it will automatically play? or i need to add a code to display the pixels?

**Comment by Yosef-Bunick** [comment]
how did you do it? what was the file called in the code that you uploaded? File f;? i should name a file f and put it on the sd card?

**Comment by Yosef-Bunick** [comment]
i am using this device esp32 with tft touch screen , the link on the sight is > https://drive.google.com/file/d/1cKDMyiLHLAAbfMAijbW-hTFzugjSr0vd/view

**Comment by bitbank2** [comment]
I'm sorry Yosef, but if you don't understand how to write code for Arduino it will mean I have to write this for you. Your questions indicate you lack an understanding of how to program the ESP32. I understand how frustrating this can be, but this is not the right place to learn how to program.

**Comment by Yosef-Bunick** [comment]
yea, no my English isn't to good, my code compiles like almost , 
can you take a look at this code and tell me what im doing wrong ? 
#include <TFT_eSPI.h>
#include <AnimatedGIF.h>
#include "SPIFFS.h"

TFT_eSPI tft = TFT_eSPI();

AnimatedGIF gif;

void setup() {
  tft.init();
  tft.setRotation(1);

  if(!SPIFFS.begin(true)) {
    Serial.println(" Error");
    return;
  }
  
  File gifFile = SPIFFS.open("orb.gif", "r");

  gif.init(&gifFile);
  gif.play();
}

void loop() {
  if (gif.isComplete()) {
    gif.rewind();
    gif.play();
  }

  tft.pushImage(0, 0, gif.width(), gif.height(), gif.frameBuffer());
}

**Comment by bitbank2** [comment]
I don't know what's wrong with your code because it looks like you're not using my AnimatedGIF library. The methods you're calling - init(), play(), rewind(), isComplete() don't exist in my library. Maybe you're using someone else's GIF library or a wrapper on top of mine. I cannot help you with that.

**Comment by Yosef-Bunick** [comment]
what methods can i call in your library? is there a list somewhere?

**Comment by Yosef-Bunick** [comment]
I gave up the old board, if I buy a lilygo ttgo esp32 s3 st7789 is that compatible with the retrotv? I want to make sure I get the right one.

**Comment by bitbank2** [comment]
Hi Yosef,
I've never heard of "retrotv", so I can't answer that question. My AnimateGIF library should work on any CPU with enough RAM.
