### ISSUE TITLE
Mac Help

### ISSUE THREAD

**Issue by AdaoH3** [bitbank2/image_to_c#9]
How would I use this for mac? Sorry if I missed documentation anywhere explaining.

**Comment by bitbank2** [comment]
I work almost exclusively on the Mac, so all of my software is for Mac first, Linux second and Windows as a last resort.

I don't like to distribute pre-built executables for my open source projects. You need to install XCode and its command line tools and then simply run "make" from a command prompt in the project root directory. It will create the executable which can then be run from the command line. I was thinking it might be handy to have a GUI version, but it's 10x as much work to get it running.
I hope this helps clarify things.

**Comment by AdaoH3** [comment]
Thanks for responding so fast. I installed X code and got the main.o file, but how would I convert a gif to a .h from here? I am getting a permission denied when trying to execute main.o with `./main.o badger.gif > out.h`. Sorry if it's a bit annoying I am new to this.

**Comment by bitbank2** [comment]
The executable created by the makefile is called image_to_c. From the command prompt type:

./image_to_c badger.gif > out.h
